language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6" 
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install authres pynacl
  - python setup.py install
# command to run tests
script:
  - python test.py
